use_v3: false
weights: ''
cfg: /root/autodl-tmp/project/YOLOv5Jittor/configs/yolov5s.yaml
data: /root/autodl-tmp/project/NWPU/data.yaml
hyp: /root/autodl-tmp/project/YOLOv5Jittor/data/hyp.scratch.yaml
epochs: 150
batch_size: 32
img_size:
- 512
- 512
rect: false
no_cuda: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
multi_scale: false
single_cls: false
adam: false
log_imgs: 16
log_artifacts: false
workers: 0
project: /root/autodl-tmp/project/YOLOv5Jittor/runs/train
name: exp
exist_ok: false
quad: false
mode: train
teacher_cfg: ''
teacher_weights: ''
alpha: 0.01
save_dir: /root/autodl-tmp/project/YOLOv5Jittor/runs/train/exp2
